export const CarViewData = [
  {
    name: 'Alfa Romeo',
    models: [
      '33',
      '75',
      '145',
      '146',
      '147',
      '155',
      '156',
      '156 Crosswagon',
      '159',
      '164',
      '166',
      'Alfetta',
      'Brera',
      'a',
      'etta',
      'GT',
      'GTV',
      'MiTo',
      'Spider',
      'Stelvio',
      'Tonale',
    ],
  },
  { name: 'Alpina', models: ['B3', 'B6'] },
  { name: 'Aro', models: ['Series 10'] },
  {
    name: 'Audi',
    models: [
      '80',
      '90',
      '100',
      'A1',
      'A2',
      'A3',
      'A4',
      'A4 Allroad',
      'A5',
      'A6',
      'A6 Allroad',
      'A7',
      'A8',
      'e-tron',
      'Q2',
      'Q3',
      'Q5',
      'Q7',
      'Q8',
      'Quattro',
      'R8',
      'RS3',
      'RS5',
      'RS6',
      'RS e-tron GT',
      'RS Q3',
      'RS Q8',
      'S1',
      'S3',
      'S4',
      'S5',
      'S6',
      'S7',
      'S8',
      'SQ5',
      'SQ7',
      'SQ8',
      'TT',
      'TTS',
      'V8',
    ],
  },
  { name: 'Austin', models: ['MK', 'Moris Marina'] },
  { name: 'Bentley', models: ['Bentyaga', 'Continental'] },
  {
    name: 'BMW',
    models: [
      '114',
      '116',
      '118',
      '120',
      '123',
      '125',
      '214',
      '216',
      '218',
      '220',
      '225',
      '315',
      '316',
      '318',
      '318 GT',
      '320',
      '320 GT',
      '323',
      '324',
      '325',
      '325 GT',
      '328',
      '330',
      '330 GT',
      '335',
      'Compact',
      '418',
      '420',
      '425',
      '428',
      '435',
      '440',
      '518',
      '520',
      '520 GT',
      '523',
      '524',
      '525',
      '528',
      '530',
      '530 GT',
      '535',
      '535 GT',
      '540',
      '545',
      '550',
      '630',
      '630 GT',
      '635',
      '640',
      '645',
      '650',
      '725',
      '728',
      '730',
      '735',
      '740',
      '745',
      '750',
      '760',
      '840',
      '850',
      'i3',
      'i8',
      'M 135i',
      'M 235i',
      'M 340i',
      'M550',
      'M 550i',
      'M2',
      'M3',
      'M4',
      'M5',
      'M8',
      'X3 M',
      'X4 M',
      'X5 M',
      'X6 M',
      'X1',
      'X2',
      'X3',
      'X4',
      'X5',
      'X6',
      'X7',
      'Z3',
      'Z4',
      '1602',
      '2002',
    ],
  },
  { name: 'Buick', models: ['Century'] },
  { name: 'Cadilac', models: ['BLS', 'Escalade', 'Seville', 'SRX'] },
  { name: 'Chery', models: ['Ego', 'Tengo', 'Tigo'] },
  {
    name: 'Chevrolet',
    models: [
      'Alero',
      'Aveo',
      'Camaro',
      'Captiva',
      'Cruze',
      'Epica',
      'Evanda',
      'Kalos',
      'Lacetti',
      'Lumina',
      'Malibu',
      'Matiz',
      'Nubira',
      'Orlando',
      'Spark',
      'Suburban',
      'Tacuma',
      'Trailblazer',
      'Trax',
    ],
  },
  {
    name: 'Chrysler',
    models: [
      '300M',
      '300C',
      'Crossfire',
      'Grand Voyager',
      'Neon',
      'Pacifica',
      'PT Cruiser',
      'Sebring',
      'Stratus',
      'Sunbeam',
      'Voyager',
    ],
  },
  {
    name: 'Citroen',
    models: [
      '2CV',
      'Ami',
      'AX',
      'ngo',
      'BX',
      'C-Aircross',
      'C-Crosser',
      'C-ELYSEE',
      'C-Zero',
      'C1',
      'C2',
      'C3',
      'C3 Aircross',
      'C3 Picasso',
      'C3 pluriel',
      'C4',
      'C4 Aircross',
      'C4 Cactus',
      'C4 Grand Picasso',
      'C4 Picasso',
      'C4 SpaceTourer',
      'C5',
      'C5 Aircross',
      'C6',
      'C8',
      'C15',
      'CX',
      'DS3',
      'DS4',
      'DS5',
      'DS7',
      'Dyane',
      'Evasion',
      'GS',
      'GSA',
      'Jumpy',
      'Nemo',
      'Oltcit',
      'Saxo',
      'Visa',
      'Xantia',
      'XM',
      'Xsara',
      'Xsara Picasso',
      'ZX',
    ],
  },
  { name: 'Cupra', models: ['Formentor'] },
  {
    name: 'Dacia',
    models: [
      ,
      'Dokker',
      'Duster',
      'Jogger',
      'Lodgy',
      'Logan',
      'Nova',
      'Pickup',
      'Sandero',
      'Solenza',
      'Stepway',
    ],
  },
  {
    name: 'Daewoo',
    models: [
      'Espero',
      'Kalos',
      'Korando',
      'Lacetti',
      'Lanos',
      'Leganza',
      'Matiz',
      'Nexia',
      'Nubira',
      'Tacuma',
    ],
  },
  {
    name: 'Daihatsu',
    models: [
      ,
      'Applause',
      'Charade',
      'Cuore',
      'Feroza',
      'Materia',
      'Rocky',
      'Sirion',
      'Terios',
      'Trevis',
      'YRV',
    ],
  },
  {
    name: 'Dodge',
    models: [
      'Avenger',
      'Caliber',
      'Durango',
      'Journey',
      'Neon',
      'Nitro',
      'RAM',
    ],
  },
  { name: 'Ferrari', models: ['456 Italia', '599', 'F430'] },
  {
    name: 'Fiat',
    models: [
      '124 Spider',
      '125',
      '126',
      '128',
      '500',
      '500C',
      '500L',
      '500X',
      '600',
      '850',
      '1107',
      'Albea',
      'Barchetta',
      'Brava',
      'Bravo',
      'Campagnola',
      'Cinquecento',
      'Croma',
      'Doblo',
      'EVO',
      'Fiorino',
      'Freemont',
      'Grande Punto',
      'Idea',
      'Linea',
      'Marea',
      'Marengo',
      'Multipla',
      'Palio',
      'Panda',
      'Punto',
      'Qubo',
      'Ritmo',
      'Scudo',
      'Sedici',
      'Seicento',
      'Spider Europa',
      'Stilo',
      'Tempra',
      'Tipo',
      'Ulysse',
      'Uno',
    ],
  },
  {
    name: 'Ford',
    models: [
      'B-Max',
      'C-Max',
      'Capri',
      'Cortina',
      'Cougar',
      'Courier',
      'EcoSport',
      'Edge',
      'Escort',
      'Expedition',
      'Explorer',
      'F 150',
      'F 250',
      'Fiesta',
      'Focus',
      'Fusion',
      'Galaxy',
      'Granada',
      'Grand C-Max',
      'Ka',
      'Ka+',
      'Kuga',
      'Maverick',
      'Mondeo',
      'Mustang',
      'Orion',
      'Probe',
      'Puma',
      'Ranger',
      'S-Max',
      'Scorpio',
      'Sierra',
      'Street Ka',
      'Taunus',
      'Taurus',
      'Tourneo',
      'Tourneo Connect',
      'Tourneo Custom',
    ],
  },
  { name: 'GAZ', models: ['3102'] },
  { name: 'Great Wall', models: ['H5', 'Steed', 'Steed  5'] },
  {
    name: 'Honda',
    models: [
      'Accord',
      'Aerodeck',
      'Civic',
      'Concerto',
      'CR-V',
      'CR-Z',
      'FR-V',
      'HR-V',
      'Insight',
      'Jazz',
      'Prelude',
      'Stream',
    ],
  },
  { name: 'Hummer', models: ['H2', 'H3'] },
  {
    name: 'Hyundai',
    models: [
      'Accent',
      'Atos',
      'Bayon',
      'Coupe',
      'Elantra',
      'Galloper',
      'Genesis',
      'Getz',
      'H 1',
      'i10',
      'i20',
      'i30',
      'i40',
      'Ioniq',
      'ix20',
      'ix35',
      'ix55',
      'Kona',
      'Lantra',
      'Matrix',
      'Pony',
      'S-Coupe',
      'Santa Fe',
      'Sonata',
      'Sonica',
      'Staria',
      'Terracan',
      'Trajet',
      'Tucson',
      'Veloster',
      'Venue',
    ],
  },
  { name: 'Infiniti', models: ['EX30', 'FX30', 'Q70', 'QX30'] },
  { name: 'Isuzu', models: ['D-Max', 'Trooper'] },
  {
    name: 'Jaguar',
    models: [
      'E-Pace',
      'E-Type',
      'F-Type',
      'F pace',
      'S-Type',
      'X-Type',
      'XE',
      'XF',
      'XJ',
      'XJ6',
      'XJ12',
      'XK8',
    ],
  },
  {
    name: 'Jeep',
    models: [
      'Cherokee',
      'Commander',
      'Compass',
      'Grand Cherokee',
      'Liberty',
      'Patriot',
      'Renegade',
      'Willys',
      'Wrangler',
    ],
  },
  {
    name: 'Kia',
    models: [
      'Carens',
      'Carnival',
      'cee`d',
      'cee`d sw',
      'Cerato',
      'Clarus',
      'EV6',
      'Picanto',
      'pro_cee`d',
      'Rio',
      'Rocsta',
      'Sephia',
      'Shuma',
      'Sorento',
      'Soul',
      'Spectra',
      'Sportage',
      'Stonic',
      'Venga',
      'XCeed',
    ],
  },
  {
    name: 'Lada',
    models: [
      '110',
      '111',
      '112',
      '1200',
      '1300',
      '1500',
      '1600',
      '2101',
      '2103',
      '2104',
      '2105',
      '2107',
      'Aleko',
      'Kalina',
      'Niva',
      'Riva',
      'Samara',
      'Vesta',
    ],
  },
  { name: 'Lamborghini', models: ['Adventador', 'Urus'] },
  {
    name: 'Lancia',
    models: [
      'Dedra',
      'Delta',
      'Flavia',
      'Kappa',
      'Lybra',
      'Musa',
      'Phedra',
      'Thema',
      'Thesis',
      'Ypsilon',
    ],
  },
  {
    name: 'Land Rover',
    models: [
      'Defender',
      'Discovery',
      'Discovery Sport',
      'Freelander',
      'Range Rover',
      'Range Rover Autobiography',
      'Range Rover Evoque',
      'Range Rover Sport',
      'Range Rover Velar',
      'Range Rover Vogue',
      'Seria II',
      'Seria III',
    ],
  },
  {
    name: 'Lexus',
    models: [
      'CT 200h',
      'GS',
      'GS 300',
      'IS',
      'IS 200',
      'IS 220',
      'IS 250',
      'IS 300',
      'LS',
      'LS 460',
      'RX',
      'RX 300',
      'RX 350',
      'RX 400',
    ],
  },
  { name: 'Lincoln', models: ['Continental', 'Navigator', 'Town car'] },
  { name: 'Linzda', models: ['M3'] },
  { name: 'Mahindra', models: ['Bolero', 'CJ', 'Goa'] },
  {
    name: 'Maserati',
    models: ['4200', 'Ghibli', 'Granturismo', 'Levante', 'Quattroporte'],
  },
  {
    name: 'Mazda',
    models: [
      '2',
      '3',
      '5',
      '6',
      '121',
      '323',
      '626',
      'B 250',
      'BT-50',
      'CX-3',
      'CX-5',
      'CX-7',
      'CX-30',
      'Demio',
      'MPV',
      'MX-3',
      'MX-5',
      'MX-6',
      'Premacy',
      'RX-7',
      'RX-8',
      'Tribute',
      'Xedos',
    ],
  },
  {
    name: 'Mercedes Benz',
    models: [
      '180',
      '190',
      'A 140',
      'A 150',
      'A 160',
      'A 170',
      'A 180',
      'A 190',
      'A 200',
      'A 220',
      'A 250',
      'A 35 AMG',
      'A 45 AMG',
      'B 150',
      'B 160',
      'B 170',
      'B 180',
      'B 200',
      'C 160',
      'C 180',
      'C 200',
      'C 220',
      'C 240',
      'C 250',
      'C 270',
      'C 280',
      'C 300',
      'C 320',
      'C 43 AMG',
      'C 63 AMG',
      'CE 200',
      'CE 300',
      'Citan',
      'CLA 180',
      'CLA 180 Shooting Brake',
      'CLA 200',
      'CLA 200 Shooting Brake',
      'CLA 220',
      'CLA 250',
      'CLA 45 AMG',
      'CL 180',
      'CL 500',
      'CL 600',
      'CL 63 AMG',
      'CLC 180',
      'CLC 200',
      'CLC 220',
      'CLK 200',
      'CLK 220',
      'CLK 230',
      'CLK 240',
      'CLK 270',
      'CLK 320',
      'CLS 250',
      'CLS 250 Shooting Brake',
      'CLS 300',
      'CLS 320',
      'CLS 350',
      'CLS 350 Shooting Brake',
      'CLS 400',
      'CLS 450',
      'CLS 500',
      'CLS 63 AMG',
      'E 124',
      'E 200',
      'E 220',
      'E 230',
      'E 240',
      'E 250',
      'E 260',
      'E 270',
      'E 280',
      'E 290',
      'E 300',
      'E 320',
      'E 350',
      'E 400',
      'E 43 AMG',
      'E 53 AMG',
      'E 63 AMG',
      'EQA',
      'EQB',
      'EQC 400',
      'EQE',
      'EQS',
      'G 300',
      'G 320',
      'G 350',
      'G 400',
      'G 500',
      'G 55 AMG',
      'G 63 AMG',
      'GL 320',
      'GL 350',
      'GL 420',
      'GL 450',
      'GL 500',
      'GLA 45 AMG',
      'GLA 180',
      'GLA 200',
      'GLA 220',
      'GLB 200',
      'GLC 43 AMG',
      'GLC 63',
      'GLC 200',
      'GLC 220',
      'GLC 250',
      'GLC 300',
      'GLE 43 AMG',
      'GLE 53 AMG',
      'GLE 63 AMG',
      'GLE 250',
      'GLE 300',
      'GLE 350',
      'GLE 400',
      'GLE 580',
      'GLK 200',
      'GLK 220',
      'GLK 250',
      'GLK 320',
      'GLK 350',
      'GLS 63 AMG',
      'GLS 350 D',
      'GLS 400',
      'GLS 580',
      'GT',
      'GT 63 AMG',
      'ML 230',
      'ML 250',
      'ML 270',
      'ML 280',
      'ML 320',
      'ML 350',
      'ML 400',
      'ML 420',
      'ML 430',
      'ML 500',
      'ML 55 AMG',
      'ML 63 AMG',
      'R 280',
      'R 320',
      'R 350',
      'S 220',
      'S 250',
      'S 280',
      'S 300',
      'S 320',
      'S 350',
      'S 400',
      'S 430',
      'S 450',
      'S 500',
      'S 550',
      'S 560 SEL',
      'S 580',
      'S 600',
      'S 63 AMG',
      'SL 280',
      'SL 300',
      'SL 350',
      'SL 500',
      'SL 600',
      'SL 65 AMG',
      'SLK 200',
      'SLK 250',
      'Vaneo',
    ],
  },
  { name: 'MG', models: ['TF', 'ZR', 'ZS', 'ZT'] },
  {
    name: 'MINI',
    models: [
      '1000',
      'Clubman',
      'Cooper',
      'Cooper S',
      'Countryman',
      'John Cooper Works',
      'Paceman',
      'One',
    ],
  },
  {
    name: 'Mitsubishi',
    models: [
      '3000GT',
      'ASX',
      'Carisma',
      'Colt',
      'Eclipse',
      'Galant',
      'Grandis',
      'L200',
      'L300',
      'Lancer',
      'Outlander',
      'Pajero',
      'Pajero Pinin',
      'Pajero Sport',
      'Space Star',
      'Space Wagon',
    ],
  },
  { name: 'Moskvitch', models: ['2140', '2141'] },
  {
    name: 'Nissan',
    models: [
      '350Z',
      '370Z',
      'Almera',
      'Almera Tino',
      'Juke',
      'Leaf',
      'Micra',
      'Murano',
      'Navara',
      'Note',
      'Pathfinder',
      'Patrol',
      'Pixo',
      'Primastar',
      'Primera',
      'Pulsar',
      'Qashqai',
      'Qashqai + 2',
      'Sentra',
      'Serena',
      'Sunny',
      'Terrano',
      'Tiida',
      'X-Trail',
    ],
  },
  { name: 'NSU', models: ['Prinz'] },
  {
    name: 'Opel',
    models: [
      'Adam',
      'Agila',
      'Antara',
      'Ascona',
      'Astra',
      'Astra F',
      'Astra G',
      'Astra H',
      'Astra J',
      'Astra K',
      'Calibra',
      'Cascada',
      'Combo',
      'Commodore',
      'Corsa',
      'Corsa A',
      'Corsa B',
      'Corsa C',
      'Corsa D',
      'Corsa E',
      'Corsa F',
      'Crossland X ',
      'Frontera',
      'GT',
      'Grandland X',
      'Insignia',
      'Kadett',
      'Karl',
      'Meriva',
      'Monterey',
      'Mokka',
      'Mokka X',
      'Omega',
      'Rekord',
      'Senator',
      'Signum',
      'Tigra',
      'Vauxall',
      'Vectra',
      'Vectra A',
      'Vectra B',
      'Vectra C',
      'Zafira',
    ],
  },
  {
    name: 'Peugeot',
    models: [
      '104',
      '106',
      '107',
      '108',
      '204',
      '205',
      '206',
      '206 plus',
      '207',
      '208',
      '301',
      '305',
      '306',
      '307',
      '308',
      '405',
      '406',
      '407',
      '504',
      '505',
      '508',
      '508 RXH',
      '605',
      '607',
      '806',
      '807',
      '1007',
      '2008',
      '3008',
      '4007',
      '4008',
      '5008',
      'Bipper',
      'Expert',
      'iOn',
      'Partner',
      'Ranch',
      'RCZ',
      'Traveller',
    ],
  },
  {
    name: 'Porsche',
    models: [
      '718',
      '911',
      '924',
      '928',
      '944',
      'Boxster',
      'Cayenne',
      'Cayman',
      'Macan',
      'Panamera',
      'Taycan',
    ],
  },
  {
    name: 'Renault',
    models: [
      'Captur',
      'Clio',
      'Espace',
      'Express',
      'Fluence',
      'Grand Espace',
      'Grand Modus',
      'Grand Scenic',
      'Kadjar',
      'Kangoo',
      'Koleos',
      'Laguna',
      'Latitude',
      'Megane',
      'Modus',
      'R 4',
      'R 5',
      'R 9',
      'R 10',
      'R 11',
      'R 18',
      'R 19',
      'R 21',
      'R 25',
      'RX',
      'Safrane',
      'Scenic',
      'Talisman',
      'Thalia',
      'Twingo',
      'Twizy',
      'Vel Satis',
      'Zoe',
    ],
  },
  {
    name: 'Saab',
    models: [
      '25',
      '45',
      '75',
      '200',
      '216',
      '220',
      '400',
      '600',
      '618',
      '620',
      'Streetwise',
    ],
  },
  {
    name: 'Seat',
    models: [
      'Alhambra',
      'Altea',
      'Altea XL',
      'Arona',
      'Arosa',
      'Ateca',
      'Cordoba',
      'Exeo',
      'Ibiza',
      'Inca',
      'Leon',
      'Mii',
      'Tarraco',
      'Toledo',
    ],
  },
  { name: 'Smart', models: ['ForFour', 'ForTwo', 'Roadster'] },
  {
    name: 'Subaru',
    models: [
      'Forester',
      'Impreza',
      'Justy',
      'Legacy',
      'Outback',
      'Trezia',
      'Tribeca',
      'XT',
      'XV',
    ],
  },
  {
    name: 'Suzuki',
    models: [
      'Alto',
      'Baleno',
      'Celerio',
      'Grand Vitara',
      'Ignis',
      'Jimny',
      'Liana',
      'Maruti',
      'SJ Samurai',
      'Splash',
      'Swift',
      'SX4',
      'SX4 S-Cross',
      'Vitara',
      'Wagon R+',
    ],
  },
  { name: 'Tata', models: ['Safari'] },
  { name: 'Tesla', models: ['Model S', 'Model 3', 'Model X'] },
  {
    name: 'Toyota',
    models: [
      '4Runner',
      'Auris',
      'Avensis',
      'Avensis Verso',
      'Aygo',
      'Aygo X',
      'C-HR',
      'Camry',
      'Carina',
      'Celica',
      'Corolla',
      'Corolla Verso',
      'GT86',
      'Highlander',
      'Hilux',
      'iQ',
      'Land Cruiser',
      'MR2',
      'Paseo',
      'Previa',
      'Prius',
      'Prius Plug In',
      'Proace City',
      'Proace City Verso',
      'RAV 4',
      'Starlet',
      'Tercel',
      'Urban Cruiser',
      'Verso',
      'Verso-S',
      'Yaris',
      'Yaris Cross',
      'Yaris Verso',
    ],
  },
  { name: 'Trabant', models: ['601'] },
  {
    name: 'Volkswagen',
    models: [
      '183',
      'Amarok',
      'Arteon',
      'Bora',
      'Buggy',
      'Buba',
      'New Beatle',
      'Caddy',
      'Corrado',
      'Cross Polo',
      'Derby',
      'EOS',
      'Fox',
      'Golf',
      'Golf 1',
      'Golf 2',
      'Golf 3',
      'Golf 4',
      'Golf 5',
      'Golf 6',
      'Golf 7',
      'Golf 8',
      'Golf Plus',
      'Golf Sportsvan',
      'Jetta',
      'Lupo',
      'Passat',
      'Passat B1',
      'Passat B2',
      'Passat B3',
      'Passat B4',
      'Passat B5',
      'Passat B5.5',
      'Passat B6',
      'Passat B7',
      'Passat B7 Alltrack',
      'Passat B8',
      'Passat B8 Alltrack',
      'Passat CC',
      'Phaeton',
      'Polo',
      'Scirocco',
      'Sharan',
      'T-Cross',
      'T-Roc',
      'Taigo',
      'Tiguan',
      'Touareg',
      'Touran',
      'up!',
      'Vento',
    ],
  },
  {
    name: 'Volvo',
    models: [
      '240',
      '244',
      '264',
      '340',
      '460',
      '740',
      '745',
      '760',
      '850',
      '945',
      '960',
      'Amazon',
      'C30',
      'C70',
      'S40',
      'S60',
      'S80',
      'S90',
      'V40',
      'V50',
      'V60',
      'V70',
      'V90',
      'XC40',
      'XC60',
      'XC70',
      'XC90',
    ],
  },
  {
    name: 'Zastava',
    models: [
      '10',
      '101',
      '128',
      '1300',
      '1500',
      '750',
      '850',
      'Florida',
      'Florida In',
      'Koral',
      'Koral In',
      'Poly',
      'Skala 55',
      'Yugo',
      'Yugo 45',
      'Yugo 55',
      'Yugo 60',
      'Yugo 65',
      'Yugo Cabrio',
      'Yugo Ciao',
      'Yugo In L',
      'Yugo Tempo',
    ],
  },
  {
    name: 'Škoda',
    models: [
      '100',
      '105',
      '120',
      '1000 MB',
      'Citigo',
      'Fabia',
      'Favorit',
      'Felicia',
      'Kamiq',
      'Karoq',
      'Kodiaq',
      'Octavia',
      'Praktik',
      'Rapid',
      'Roomster',
      'Scala',
      'Superb',
      'Yeti',
    ],
  },
];
